# Generated by Django 3.1.4 on 2021-01-12 07:08

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passenger_berth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='passenger_id',
            field=models.CharField(default=users.models.get_code, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
