# Generated by Django 3.1.3 on 2020-12-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201207_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='invalid@gmail.com', max_length=100, unique=True),
        ),
    ]
