# Generated by Django 3.1.3 on 2020-12-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201207_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='invalid@gmail.com', max_length=100, unique=True),
        ),
    ]
