# Generated by Django 3.1.3 on 2021-01-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210112_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='train_route',
            new_name='route_table',
        ),
        migrations.AddField(
            model_name='train',
            name='route',
            field=models.ManyToManyField(to='booking.Station'),
        ),
    ]
