# Generated by Django 3.1.3 on 2021-01-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_train_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockedseat',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
