# Generated by Django 3.1.3 on 2021-01-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_lockedseat_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='transaction_id',
            field=models.CharField(default=10, max_length=10),
        ),
    ]
