# Generated by Django 3.1.3 on 2020-11-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=100)),
                ('station_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField()),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('route', models.ManyToManyField(to='booking.Station')),
            ],
        ),
    ]
