# Generated by Django 3.1.3 on 2021-01-12 08:15

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210112_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default=booking.models.get_code, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
