# Generated by Django 3.1.3 on 2020-11-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20201126_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
