# Generated by Django 3.1.3 on 2021-01-12 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210112_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='route',
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('train_id', models.CharField(default=None, max_length=10)),
                ('route_index', models.PositiveIntegerField(default=1)),
                ('expected_time', models.DateTimeField(default=None)),
                ('actual_time', models.DateTimeField(default=None)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.station')),
            ],
        ),
        migrations.AddField(
            model_name='train',
            name='train_route',
            field=models.ManyToManyField(to='booking.Route'),
        ),
    ]
