# Generated by Django 3.1.3 on 2021-01-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210112_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='route_table',
            field=models.ManyToManyField(null=True, to='booking.Route'),
        ),
    ]
