# Generated by Django 3.1.3 on 2020-12-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_ticket_coach_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='remaining_seats',
            field=models.IntegerField(default=50),
        ),
    ]
