# Generated by Django 3.1.3 on 2021-01-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210112_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='actual_time',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='route',
            name='expected_time',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
