# Generated by Django 3.1.3 on 2021-01-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20210112_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='departure_time',
            new_name='end_time',
        ),
    ]
